version: "3.3"

services:
  discovery:
    container_name: estuary-discovery
    image: estuaryoss/discovery:latest
    hostname: estuary-discovery
    command: bash -c "sleep 20 && /root/app/main-linux"
    environment:
      #      FLUENTD_IP_PORT: 192.168.100.12:24224
      EUREKA_SERVER: http://eureka-server:8080/eureka/v2 #your eureka server
      APP_IP_PORT: estuary-discovery:8080 #your app details: where it is and on which port. needed for service discovery and spread of tests from the test client
      HTTP_AUTH_USER: "admin"
      HTTP_AUTH_PASSWORD: "estuaryoss123!"
    ports:
      - "8081:8080"

    expose:
      - "8080"

  agent:
    image: estuaryoss/agent-java:latest
    hostname: estuary-agent
    entrypoint: bash -c "sleep 20 && java -jar -Deureka.client.enabled=true agent-exec.jar"
    environment:
      EUREKA_SERVER: http://eureka-server:8080/eureka/v2 #your eureka server
      APP_IP: estuary-agent #your app details: where it is and on which port. needed for service discovery and spread of tests from the test client
      PORT: 8080
      HTTP_AUTH_USER: "admin" #change it with env vars
      HTTP_AUTH_PASSWORD: "estuaryoss123!" #change it with env vars
    ports:
      - "8082:8080"
    expose:
      - "8080"

  eureka-server:
    image: estuaryoss/netflix-eureka:1.10.11
    hostname: eureka-server
    ports:
      - "8080:8080"
    expose:
      - "8080"
