version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  build-and-test:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          command: pip --version
          name: "pip version"
      - run:
          command: pip install -r requirements.txt
          name: "install requirements"
      - run:
          command: pip install pypiwin32
          name: "install pypiwin32"
      - run:
          command: python --version
          name: "python version"
      - run:
          command: python -m PyInstaller --onefile --clean --add-data="rest/api/templates/;rest/api/templates/" main.py
          name: "build main-win"
      - run:
          command: Copy-Item "dist\main.exe" -Destination "main-win.exe"
          name: "copy main-win"
      - run:
          command: Start-Process .\main-win.exe
          name: "start main-win"
          environment:
            PORT: 8080
            VARS_DIR: inputs/variables
            TEMPLATES_DIR: inputs/templates
      - run:
          command: ping -n 10 127.0.0.1
          name: "wait some time"
      - run:
          command: python -m unittest discover tests/rest "*_test.py"
          name: "run integration tests"
          environment:
            ENABLE_HTTPS: false
      - store_artifacts:
          path: main-win.exe

workflows:
  main:
    jobs:
      - build-and-test
