class EnvConstants:
    EUREKA_SERVER = "EUREKA_SERVER"
    APP_IP_PORT = "APP_IP_PORT"
    FLUENTD_IP_PORT = "FLUENTD_IP_PORT"
    HTTP_AUTH_TOKEN = "HTTP_AUTH_TOKEN"
    TEMPLATES_DIR = "TEMPLATES_DIR"
    VARS_DIR = "VARS_DIR"
    WORKSPACE = "WORKSPACE"
    PORT = "PORT"
