import os


class Constants:
    DOCKER_PATH = "/tmp/"

    SUCCESS = "1000"
    JINJA2_RENDER_FAILURE = "1001"
    GET_EUREKA_APPS_FAILED = "1002"
    GET_CONTAINER_ENV_VAR_FAILURE = "1003"
    EUREKA_APP_NOT_SUPPORTED = "1004"
    GET_TESTS_FAILED = "1005"
    GET_DEPLOYMENTS_FAILED = "1006"

